# Generated by Django 2.1.5 on 2019-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='setlist',
        ),
        migrations.AddField(
            model_name='setlist',
            name='song',
            field=models.ManyToManyField(to='music_tour.Song'),
        ),
    ]
