# Generated by Django 2.1.5 on 2019-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_tour', '0002_auto_20190307_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='setlist',
            field=models.ManyToManyField(to='music_tour.Setlist'),
        ),
    ]
